author = Artur Tarassow
email = atecon@cryptolab.net
version = 0.1
date = 2018-11-11
description = Rolling Time-Series Statistics
tags = C53
min-version = 2017a
data-requirement = needs-time-series-data
gui-main = rolling_ts
label = Rolling Time-series stats
menu-attachment = Add
public = rolling_ts rvec2series
menu-only = rolling_ts_gui
help = RollingStats.txt
sample-script = RollingStats_sample.inp
