author = Artur Tarassow
email = atecon@posteo.de
version = 1.1
date = 2024-06-05
description = Compute moving-window statistics
tags = C10
min-version = 2023b
data-requirement = needs-time-series-data
public = moving_stats movstats
gui-main = movstats
label = Moving time-series statistics
menu-attachment = MAINWIN/Add
help = RollingStats_help.md
sample-script = RollingStats_sample.inp
