author = Artur Tarassow
email = atecon@posteo.de
version = 1.0
date = 2023-02-01
description = Compute moving-window statistics
tags = C10
min-version = 2021c
data-requirement = needs-time-series-data
public = rolling rolling_gui
gui-main = rolling_gui
menu-only = rolling_gui
label = Moving time-series statistics
menu-attachment = MAINWIN/Add
help = RollingStats_help.txt
sample-script = RollingStats_sample.inp
